services:
  postgres:
    image: postgres:15
    container_name: lumio_files_postgres
    environment:
      POSTGRES_DB: files
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - postgres_data_files:/var/lib/postgresql/data

volumes:
  postgres_data_files:
