services:
  postgres:
    image: postgres:15
    container_name: lumio_payments_postgres
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5434:5432'
    volumes:
      - postgres_data_payments:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: lumio_payments_redis
    ports:
      - '6380:6379'
    volumes:
      - redis_data_payments:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  postgres_data_payments:
  redis_data_payments:
