services:
  postgres:
    image: postgres:15
    container_name: lumio_payments_postgres
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5434:5432'
    volumes:
      - postgres_data_payments:/var/lib/postgresql/data

volumes:
  postgres_data_payments:
