services:
  postgres:
    image: postgres:15
    container_name: lumio_postgres
    environment:
      POSTGRES_DB: lumio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lumio_network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: lumio_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - lumio_network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  lumio_network:
