services:
  postgres:
    image: postgres:15
    container_name: lumio_postgres
    environment:
      POSTGRES_DB: lumio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
