def app
pipeline {
    agent any
    environment {
        ENV_TYPE = "production"
        PORT = 4121
        NAMESPACE = "lumio-su"
        REGISTRY_HOSTNAME = "senorian3"
        PROJECT = "lumio-back-end"
        SERVICE="lumio"
        REGISTRY = "registry.hub.docker.com"
        DEPLOYMENT_NAME = "lumio-back-end-deployment"
        IMAGE_NAME = "${env.BUILD_ID}_${env.ENV_TYPE}_${env.GIT_COMMIT}"
        DOCKER_BUILD_NAME = "${env.REGISTRY_HOSTNAME}/${env.PROJECT}:${env.IMAGE_NAME}"
    }

    stages {
        stage('Clone repository') {
            steps {
                checkout scm
            }
        }


         stage('Setup Node.js') {
            steps {
                script {
                    sh '''
                       echo "=== Setting up Node.js environment ==="
                       
                       export NVM_DIR="$HOME/.nvm"
                       [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
                       
                       nvm install 20.17.0
                       nvm use 20.17.0
                       
                       echo "Node version: $(node --version)"
                       echo "NPM version: $(npm --version)"
                       
                       echo "✅ Node.js setup completed"
                    '''
                }
            }
        }

         stage('Generate Prisma Client') {
            steps {
               script {
                   sh '''
                   echo "=== Generating Prisma Client ===" 
                   yarn install
                   
                   npx prisma generate --schema apps/lumio/src/prisma/schema.prisma
                   
                   ls -la generated/ || echo "generated folder not found"
                   
                   echo "✅ Prisma Client generated successfully"
                '''
            }
        }
    }

        stage('Unit tests') {
            steps {
                script {
                    sh '''
                       echo "Unit tests are not implemented yet. Skipping..." 
                    '''
                }
            }
        }
        stage('e2e tests') {
            steps {
                script {
                    sh '''
                     echo "e2e tests are not implemented yet. Skipping..."
                    '''
                }
            }
        }
        stage('Build docker image') {
            steps {
                echo "Build image started..."
                    script {
                       app = docker.build("${env.DOCKER_BUILD_NAME}", "--build-arg service=${env.SERVICE} --build-arg port=${env.PORT} -f ./apps/${env.SERVICE}/Dockerfile ./")
                    }
                echo "Build image finished..."
            }
        }
        stage('Push docker image') {
             steps {
                 echo "Push image started..."
                     script {
                        docker.withRegistry("https://${env.REGISTRY}", 'lumio-su') {
                            app.push("${env.IMAGE_NAME}")
                        }
                     }
                 echo "Push image finished..."
             }
       }
       stage('Delete image local') {
             steps {
                 script {
                    sh "docker rmi -f ${env.DOCKER_BUILD_NAME}"
                 }
             }
        }
        stage('Preparing deployment') {
             steps {
                 echo "Preparing started..."
                     sh 'ls -ltr'
                     sh 'pwd'
                     sh "chmod +x ./apps/${env.SERVICE}/preparingDeploy.sh"
                     sh "./apps/${env.SERVICE}/preparingDeploy.sh ${env.REGISTRY_HOSTNAME} ${env.PROJECT} ${env.IMAGE_NAME} ${env.DEPLOYMENT_NAME} ${env.PORT} ${env.NAMESPACE}"
                     sh "cat ./apps/${env.SERVICE}/deployment.yaml"
             }
        }
        stage('Deploy to Kubernetes') {
             steps {
                 withKubeConfig([credentialsId: 'prod-kubernetes']) {
                    sh "kubectl apply -f ./apps/${env.SERVICE}/deployment.yaml"
                    sh "kubectl rollout status deployment/${env.DEPLOYMENT_NAME} --namespace=${env.NAMESPACE}"
                    sh "kubectl get services -o wide"
                 }
             }
        }
    }
}
