export enum NotificationType {
  SUBSCRIPTION_ACTIVE = 'SUBSCRIPTION_ACTIVE',
  SUBSCRIPTION_EXPIRING_1DAY = 'SUBSCRIPTION_EXPIRING_1DAY',
  SUBSCRIPTION_EXPIRING_7DAYS = 'SUBSCRIPTION_EXPIRING_7DAYS',
  PAYMENT_WARNING = 'PAYMENT_WARNING',
}
