services:
  postgres:
    image: postgres:15
    container_name: lumio_chat_postgres
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5435:5432'
    volumes:
      - postgres_data_chat:/var/lib/postgresql/data

volumes:
  postgres_data_chat:
